version: "3"

services:
        nginx:
                image: nginx:latest
                volumes:
                   - ./conf:/etc/nginx/conf.d/
                   - ./site:/usr/share/nginx/html/
                ports:
                   - '80:80'
